stage:
	python make.py stage

.PHONY: prepare_sim_libri_css
prepare_sim_libri_css:
	python make.py prepare_sim_libri_css

.PHONY: prepare_libri_css
prepare_libri_css:
	python make.py prepare_libri_css

.PHONY: sim_libri_css
sim_libri_css:
	python make.py sim_libri_css

.PHONY: libri_css
libri_css:
	python make.py libri_css

.PHONY: ivector
ivector:
	python make.py ivector
